Update getTablesFilterByExtensions.ts
Missing view for postgis: 
https://postgis.net/docs/using_raster_dataman.html#RT_Raster_Catalog

This was an issue on my side using postgis, when I want to publish my schema using drizzle kit push, it raise this issue:
```
error: cannot drop view raster_columns because extension postgis requires it
```

With this error object:
```js
{
  length: 179,
  severity: 'ERROR',
  code: '2BP01',
  detail: undefined,
  hint: 'You can drop extension postgis instead.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dependency.c',
  line: '615',
  routine: 'findDependentObjects'
}
```

Adding the table to the extension filter should handle that.